"""Updated Questions Model with a Deleted Boolean

Revision ID: b34555670354
Revises: a0052bd4a098
Create Date: 2024-05-18 11:19:02.213489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34555670354'
down_revision = 'a0052bd4a098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
