"""empty message

Revision ID: d9b8e2acbf14
Revises: d59429946a07
Create Date: 2024-05-19 15:30:23.538041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b8e2acbf14'
down_revision = 'd59429946a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user_answers', ['answer_id'], ['answer_id'])

    # ### end Alembic commands ###
